name: Build

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build_windows:
    # The type of runner that the job will run on
    runs-on: self-hosted-windows-tinyweb

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE
      - uses: actions/checkout@v2

      - name: Compile TinyWeb with Delphi 2007
        run: |
          cd $Env:GITHUB_WORKSPACE/SRC
          & 'C:\Delphi2007\Main\bin\DCC32.EXE' @('-B', 'Tiny.dpr')

      - name: Compile TinyWeb with FreePascal 3.2.2 in ObjFPC mode
        run: |
          cd $Env:GITHUB_WORKSPACE/SRC
          & 'C:\FPC\3.2.2\bin\i386-win32\fpc.exe' @('-B', '-MObjFPC', 'Tiny.dpr')

      - name: Compile TinyWeb with FreePascal 3.2.2 in Delphi mode
        run: |
          cd $Env:GITHUB_WORKSPACE/SRC
          & 'C:\FPC\3.2.2\bin\i386-win32\fpc.exe' @('-B', '-MDelphi', 'Tiny.dpr')
